#!/usr/bin/env ruby
message_file = ARGV[0]
#message = File.read(message_file)
message = File.open(message_file){| f | f.readline}

$regex = /.\((.*)\)\: ./

if !$regex.match(message)
  puts "[Y&T] Your commit message is not formatted correctly, should like ==> aa(bb):空格cc"
  exit 1
end
